velocidades:
  crucero: 60
  evasion: 40

angulos_servo:
  recto: 90
  evasion_roja: 130 # Izquierda
  evasion_verde: 50 # Derecha

hsv_rojo:
  lower: [0, 120, 70]
  upper: [10, 255, 255]
  lower2: [170, 120, 70]
  upper2: [180, 255, 255]

hsv_verde:
  lower: [40, 40, 40]
  upper: [80, 255, 255]

hsv_magenta:
  lower: [140, 50, 50]
  upper: [170, 255, 255]

competicion:
  modo_reto: "obstaculos" # "abierto" o "obstaculos"
  sentido_giro: "horario" # "horario" o "antihorario"
  max_vueltas: 3

vision:
  min_area: 500

lidar:
  pin_servo: 18
  distancia_giro_cm: 50.0
